export const es = {
    appJS: {
        summary: "Resumen",
        transactions: "Transac...",
        wallet: "Cartera",
        settings: "Ajustes"
    },
    createUserScreen: {
        welcomeTxt: "Bienvenido a ",
        chooseLanguage: "Selecciona tu idioma",
        enterFName: "Introduce tu primer nombre",
        acceptBtn: "Aceptar"
    },
    createAccountsScreen: {
        welcome: "Hola, ",
        registerTxt: "Antes de comenzar, registremos tus cuentas líquidas (por ejemplo, tarjetas de débito, monederos digitales o efectivo).",
        registerTDC: "Podrás añadir tus tarjetas de crédito en la siguiente pantalla.",
        noAccounts: "Al menos añade una cuenta líquida",
        bank: "Banco",
        cash: "Efectivo",
        savings: "Ahorros",
        startBtn: "Siguiente",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        accountName: "Nombre de la cuenta"
    },
    createCCScreen: {
        header1: "Añade tus ",
        header2: "Tarjetas de Crédito",
        registerTxt: "Ahora, añade tus tarjetas de crédito para completar la configuración de las cuentas.", registerTDC: "Podrás añadir tus tarjetas de crédito en la siguiente pantalla.",
        onlyAdd: "Por favor, añade únicamente el monto total que debes.",
        registerTDC: "Puedes saltar esta pantalla si no tienes tarjetas de crédito.",
        bank: "Crédito Banco",
        startBtn: "Siguiente",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        accountName: "Nombre de la cuenta"
    },
    mainScreen: {
        headerDarkTxt: "Hola, ",
        rowDescription: "Balance en ",
        transferBtn: " Transferir",
        hideBtn: " Ocultar Totales",
        summaryTitle: "Resumen del Mes",
        income: "Ingresos: ",
        expenses: "Gastos: ",
    },
    transactionsScreen: {
        headerDarkTxt: "Mis ",
        headerGradientTxt: "Transacciones",
        searchPlaceHolder: "Buscar por descripción",
        selectTypeAll: "Todos",
        selectTypeIncome: "Ingresos",
        selectTypeExpenses: "Gastos",
        selectTypeLoans: "Préstamos",
        emptyListTxt: "No hay transacciones",
    },
    walletScreen: {
        headerDarkTxt: "Mi ",
        headerGradientTxt: "Cartera",
        title1: "Transferir Entre Tus Cuentas",
        title2: "Edita Tus Cuentas",
        amountTxt: "Cantidad:",
        fromTxt: "De:",
        toTxt: "A:",
        isCC: "Es Tarjeta de Crédito",
        btnTransfer: "Transferir",
        btnTransfering: "Transfiriendo...",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        modalEditAccountTitle: "Edita Una Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        saveBtnTxt: "Guardar",
        alertFailedTransferTitle: "Transacción Fallida",
        alertFailedTransferDesc: "No tienes suficientes fondos en la cuenta seleccionada.",
        alertFailedDeleAccTitle: "Error al borrar",
        alertFailedDeleAccDesc: "No se puede eliminar una cuenta con fondos existentes. Transfiere antes tus ingresos a otra cuenta."
    },
    typeTransactionScreen: {
        addIncomeTxt: "Añade un Ingreso",
        addExpenseTxt: "Añade un Gasto",
        addLoanTxt: "Hice un préstamo"
    },
    transactionScreen: {
        headerRegister: "Registra un ",
        headerEdit: "Edita un ",
        headerIncome: "Ingreso",
        headerExpense: "Gasto",
        headerLoan: "Préstamo",
        amount: "Cantidad:",
        account: "Cuenta:",
        date: "Fecha:",
        description: "Descripción",
        optional: "(Opcional):",
        saveBtn: "Guardar",
        savingTxt: "Guardando...",
        category: "Categoría:"
    },
    settingsScreen: {
        headerDarkTxt: "Mis ",
        headerGradientTxt: "Ajustes",
        changeLanguage: "Cambiar Idioma",
        descriptionLanguage: "Idioma Actual: ",
        editName: "Editar mi nombre",
        descriptionName: "Nombre Actual: ",
        changePrivacy: "Privacidad en Totales",
        descriptionPrivacy: "Oculta o muestra tus totales.",
        deleteTransactions: "Borrar Transacciones",
        descriptionTransactions: "Sólo se borrarán las transacciones.",
        deleteAll: "Borrar Todos Los Datos",
        descriptionAll: "Se reiniciará la App desde zero.",
        cancelBtn: "Cancelar",
        acceptBtn: "Aceptar",
        deleteBtn: "Borrar",
        deleteTransactionsModal: "¿Estás seguro de borrar todas tus transacciones? Tus transacciones se eliminarán para siempre.",
        deleteAllModal: "¿Estás seguro de borrar todos tus datos? La aplicación borrará todos tus datos y se eliminarán para siempre.",
        enterFName: "Introduce tu primer nombre"
    },
    transactionCard: {
        typeIncome: "Ingreso",
        typeExpense: "Gasto",
        typeLoan: "Préstamo",
        account: "Cuenta: ",
        date: "Fecha: ",
        category: "Categoría: ",
        description: "Descripción: ",
        noDescription: "No hay descripción.",
    },
    modalSelect: {
        btnAccept: 'Aceptar'
    }
}

export const en = {
    appJS: {
        summary: "Summary",
        transactions: "Transac...",
        wallet: "Wallet",
        settings: "Settings"
    },
    createUserScreen: {
        welcomeTxt: "Welcome to ",
        chooseLanguage: "Choose your language",
        enterFName: "Enter your first name",
        acceptBtn: "Accept"
    },
    createAccountsScreen: {
        welcome: "Hello, ",
        registerTxt: "Before we start, let's register your liquid accounts (e.g., debit cards, digital wallets, or cash).",
        registerTDC: "You'll be able to add your credit cards on the next screen.",
        noAccounts: "Please add at least one liquid account.",
        bank: "Bank",
        cash: "Cash",
        savings: "Savings",
        startBtn: "Next",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        accountName: "Account's Name"
    },
    createCCScreen: {
        header1: "Add your ",
        header2: "Credit Cards",
        registerTxt: "Now, let's add your credit cards to complete the account setup.",
        onlyAdd: "Please only enter the total amount you owe.",
        registerTDC: "You can skip this screen if you don't have credit cards.",
        noAccounts: "Please add at least one liquid account.",
        bank: "Bank Credit",
        startBtn: "Next",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        accountName: "Account's Name"
    },
    mainScreen: {
        headerDarkTxt: "Hello, ",
        rowDescription: "Balance in ",
        transferBtn: " Transfer",
        hideBtn: " Hide Totals",
        summaryTitle: "Monthly Summary",
        income: "Income: ",
        expenses: "Expenses: ",
    },
    transactionsScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Transactions",
        searchPlaceHolder: "Search by description",
        selectTypeAll: "All",
        selectTypeIncome: "Income",
        selectTypeExpenses: "Expenses",
        selectTypeLoans: "Loans",
        emptyListTxt: "No transactions",
    },
    walletScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Wallet",
        title1: "Transfer Between Your Accounts",
        title2: "Edit Your Accounts",
        isCC: "Is Credit Card",
        amountTxt: "Amount:",
        fromTxt: "From:",
        toTxt: "To:",
        btnTransfer: "Transfer",
        btnTransfering: "Transferring...",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        modalEditAccountTitle: "Edit an Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        saveBtnTxt: "Save",
        alertFailedTransferTitle: "Transaction Failed",
        alertFailedTransferDesc: "You do not have sufficient funds in the selected account.",
        alertFailedDeleAccTitle: "Error Deleting",
        alertFailedDeleAccDesc: "You cannot delete an account with existing funds. Please transfer your balance to another account first.",
    },
    typeTransactionScreen: {
        addIncomeTxt: "Add an Income",
        addExpenseTxt: "Add an Expense",
        addLoanTxt: "I  Lent  Money"
    },
    transactionScreen: {
        headerRegister: "Register ",
        headerEdit: "Edit ",
        headerIncome: "Income",
        headerExpense: "Expense",
        headerLoan: "Loan",
        amount: "Amount:",
        account: "Account:",
        date: "Date:",
        description: "Description",
        optional: "(Optional):",
        saveBtn: "Save",
        savingTxt: "Saving...",
        category: "Category:"
    },
    settingsScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Settings",
        changeLanguage: "Change Language",
        descriptionLanguage: "Current Language: ",
        editName: "Edit my name",
        descriptionName: "Current Name: ",
        changePrivacy: "Privacy in Totals",
        descriptionPrivacy: "Hide or show your totals.",
        deleteTransactions: "Delete Transactions",
        descriptionTransactions: "Only transactions will be deleted.",
        deleteAll: "Delete All Data",
        descriptionAll: "The app will be reset from scratch.",
        cancelBtn: "Cancel",
        acceptBtn: "Accept",
        deleteBtn: "Delete",
        deleteTransactionsModal: "Are you sure you want to delete all your transactions? Your transactions will be permanently deleted.",
        deleteAllModal: "Are you sure you want to delete all your data? The app will delete all your data and it will be permanently removed.",
        enterFName: "Enter your first name"
    },
    transactionCard: {
        typeIncome: "Income",
        typeExpense: "Expense",
        typeLoan: "Loan",
        account: "Account: ",
        date: "Date: ",
        category: "Category: ",
        description: "Description: ",
        noDescription: "No description."
    },
    modalSelect: {
        btnAccept: 'Accept'
    }
}