export const es = {
    appJS: {
        summary: "Resumen",
        transactions: "Transacciones",
        wallet: "Cartera",
        settings: "Ajustes"
    },
    createUserScreen: {
        welcomeTxt: "Bienvenido a ",
        chooseLanguage: "Selecciona tu idioma",
        enterFName: "Introduce tu primer nombre",
        acceptBtn: "Comenzar"
    },
    createAccountsScreen: {
        welcome: "Hola, ",
        registerTxt: "Antes de comenzar, registremos tus cuentas líquidas (por ejemplo, tarjetas de débito, monederos digitales o efectivo).",
        registerTDC: "Podrás añadir tus tarjetas de crédito en la siguiente pantalla.",
        noAccounts: "Al menos añade una cuenta líquida",
        bank: "Banco",
        cash: "Efectivo",
        savings: "Ahorros",
        startBtn: "Siguiente",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        accountName: "Nombre de la cuenta"
    },
    createCCScreen: {
        header1: "Añade tus ",
        header2: "Tarjetas de Crédito",
        registerTxt: "Ahora, añade tus tarjetas de crédito para completar la configuración de las cuentas.", registerTDC: "Podrás añadir tus tarjetas de crédito en la siguiente pantalla.",
        onlyAdd: "Por favor, añade únicamente el monto total que debes a cada tarjeta.",
        registerTDC: "Puedes saltar esta pantalla si no tienes tarjetas de crédito.",
        bank: "Crédito Banco",
        startBtn: "Comenzar",
        noCC: "No tengo tarjetas de crédito. (Saltar)",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        accountName: "Nombre de la cuenta"
    },
    mainScreen: {
        headerDarkTxt: "Hola, ",
        rowDescription: "Balance en ",
        transferBtn: " Transferir",
        hideBtn: " Ocultar Totales",
        summaryTitle: "Resumen del Mes",
        income: "Ingresos: ",
        expenses: "Gastos: ",
    },
    transactionsScreen: {
        headerDarkTxt: "Mis ",
        headerGradientTxt: "Transacciones",
        searchPlaceHolder: "Buscar por descripción",
        selectTypeAll: "Todas",
        selectTypeIncome: "Ingresos",
        selectTypeExpenses: "Gastos",
        emptyListTxt: "No hay transacciones",
    },
    walletScreen: {
        headerDarkTxt: "Mi ",
        headerGradientTxt: "Cartera",
        title1: "Transferir Entre Tus Cuentas",
        title2: "Edita Tus Cuentas",
        amountTxt: "Cantidad:",
        fromTxt: "De:",
        toTxt: "A:",
        isCC: "Es Tarjeta de Crédito",
        btnTransfer: "Transferir",
        btnTransfering: "Transfiriendo...",
        addAccountBtn: "Añadir Cuenta",
        modalAddAccountTitle: "Añade Una Nueva Cuenta",
        modalEditAccountTitle: "Edita Una Cuenta",
        chooseIconTxt: "Escoge Un Icono",
        cancelBtnTxt: "Cancelar",
        createBtnTxt: "Crear",
        saveBtnTxt: "Guardar",
        alertFailedTransferTitle: "Transacción Fallida",
        alertFailedTransferDesc: "No tienes suficientes fondos en la cuenta seleccionada.",
        alertSameAccountTitle: "Cuenta inválida",
        alertSameAccountDesc: "No puedes transferir a la misma cuenta.",
        alertFailedDeleAccTitle: "Error al borrar",
        alertFailedDeleAccDesc: "No se puede eliminar una cuenta con fondos existentes. Transfiere antes tus ingresos a otra cuenta.",
        deleteAccountTitle: "¿Borrar cuenta?",
        deleteAccountDesc: "Esta cuenta se eliminará para siempre, así como sus transacciones. Esta acción no se puede deshacer.",
    },
    typeTransactionScreen: {
        addIncomeTxt: "Añade un Ingreso",
        addExpenseTxt: "Añade un Gasto",
    },
    iaTransactionsScreen: {
        title: "Transacción por voz",
        subtitleIdle: "Describe tu transacción",
        subtitleRecording: "Escuchando...",
        subtitleProcessing: "Procesando...",
        hintIdle: "Toca para hablar",
        hintRecording: "Toca para detener y procesar",
        retryBtn: "Volver a grabar",
        helpBtn: "?",
        helpTitle: "Bienvenido al modelo de ExpensIA",
        helpHowToUseTitle: "Cómo usar",
        helpHowToUseBody: "Di una sola transacción por grabación. Incluye: monto, tipo (ingreso o gasto), cuenta, fecha y un detalle breve. Puedes usar lenguaje natural de fecha como 'ayer', 'antier' o 'hace 15 días'. Por ejemplo: 'Gasté 250 pesos en comida ayer con mi BBVA'.",
        helpLimitationsTitle: "Limitaciones",
        helpLimitationsBody: "ExpensIA solo puede procesar una transacción por petición, así que evita mencionar múltiples movimientos en una sola grabación.",
        helpCloseBtn: "Entendido",
        alertBackendTitle: "Respuesta del backend",
        alertNoResponse: "Sin respuesta",
        alertOkBtn: "OK",
        errorStartRecording: "No se pudo iniciar la grabación",
        errorProcessing: "Error al procesar",
        errorGeneric: "Algo salió mal",
        errorRetry: "No se pudo reiniciar la grabación",
        loadingMsgs: [
            "Haciendo magia con tus finanzas ✨",
            "Negociando con el universo para subir tu saldo...",
            "Contando tus pesitos... dos veces por seguridad 🧐",
            "Hablando con mi contador imaginario...",
            "Optimizando tu futuro millonario (sin presión)...",
            "Convenciendo a la IA de no gastarse tu dinero...",
            "Analizando si eso fue gasto... o inversión 👀",
            "Buscando ese ticket que juraste no perder...",
            "Haciendo que Excel se sienta orgulloso de ti 📊",
            "Calculando cuántos cafés podrías haber evitado ☕",
            "Preguntándole a ChatGPT… ah no, yo soy ExpensIA 🤖",
            "Ajustando tus finanzas con precisión quirúrgica...",
            "Simulando tu vida como millonario 💸",
            "Revisando si eso entra en 'gastos hormiga'...",
            "Consultando con los dioses del presupuesto...",
        ],
    },
    transactionScreen: {
        iaBannerLabel: "Obtenido de IA",
        iaBannerTranscript: "Lo que dijiste:",
        headerRegister: "Registra un ",
        headerEdit: "Edita un ",
        headerIncome: "Ingreso",
        headerExpense: "Gasto",
        amount: "Cantidad:",
        account: "Cuenta:",
        date: "Fecha:",
        description: "Descripción",
        optional: "(Opcional):",
        saveBtn: "Guardar",
        savingTxt: "Guardando...",
        category: "Categoría:"
    },
    settingsScreen: {
        headerDarkTxt: "Mis ",
        headerGradientTxt: "Ajustes",
        changeLanguage: "Cambiar Idioma",
        descriptionLanguage: "Idioma Actual: ",
        editName: "Editar mi nombre",
        descriptionName: "Nombre Actual: ",
        changePrivacy: "Privacidad en Totales",
        descriptionPrivacy: "Oculta o muestra tus totales.",
        customCategories: "Mis Categorías",
        descriptionCategories: "Crea y gestiona tus categorías.",
        deleteTransactions: "Borrar Transacciones",
        descriptionTransactions: "Sólo se borrarán las transacciones.",
        deleteAll: "Borrar Todos Los Datos",
        descriptionAll: "Se reiniciará la App desde zero.",
        cancelBtn: "Cancelar",
        acceptBtn: "Aceptar",
        deleteBtn: "Borrar",
        deleteTransactionsModal: "¿Estás seguro de borrar todas tus transacciones? Tus transacciones se eliminarán para siempre.",
        deleteAllModal: "¿Estás seguro de borrar todos tus datos? La aplicación borrará todos tus datos y se eliminarán para siempre.",
        enterFName: "Introduce tu primer nombre",
        logout: "Cerrar sesión",
        logoutSession: "Sesión:",
        logoutModalTitle: "¿Cerrar sesión?",
        logoutModalDesc: "Tu sesión en la nube se cerrará en este dispositivo. Tus datos locales no se eliminan.",
    },
    customCategoriesScreen: {
        headerDark: "Mis ",
        headerGradient: "Categorías",
        sectionExpenses: "Gastos",
        sectionIncome: "Ingresos",
        empty: "No tienes categorías personalizadas aún.",
        deleteCatTitle: "¿Borrar categoría?",
        deleteCatDesc: "La categoría se eliminará. Las transacciones existentes no se verán afectadas.",
    },
    createCategorySheet: {
        createTitle: "Nueva categoría",
        editTitle: "Editar categoría",
        nameLabel: "Nombre",
        namePlaceholder: "Ej: Gym, Mascota...",
        typeLabel: "Tipo",
        typeExpense: "Gasto",
        typeIncome: "Ingreso",
        iconLabel: "Ícono",
        saveBtn: "Guardar",
        saving: "Guardando...",
        newCategoryBtn: "Nueva categoría",
        myCategoriesLabel: "Mis categorías",
    },
    transactionCard: {
        typeIncome: "Ingreso",
        typeExpense: "Gasto",
        account: "Cuenta: ",
        date: "Fecha: ",
        category: "Categoría: ",
        description: "Descripción: ",
        noDescription: "No hay descripción.",
    },
    modalSelect: {
        chooseAccount: 'Seleccione su cuenta'
    },
    monthYearPicker: {
        title: "Mes y año",
        confirm: "Aceptar",
        cancel: "Cancelar",
    },
    modalDelete: {
        titleDeleteTran: "¿Estás seguro de borrar la transacción?",
        descriptionDeleteTran: "Tu transacción se borrará para siempre y se ajustarán los totales de tus cuentas.",
        cancelBtn: "Cancelar",
        deleteBtn: "Borrar",
    },
    toast: {
        savedLocal: "Guardado",
        saveFailed: "No se pudo guardar",
        savedSynced: "Guardado y sincronizado",
        savedOfflineTitle: "Guardado sin conexión",
        savedOfflineSub: "Se sincronizará al recuperar internet",
        serverErrorTitle: "Error del servidor",
        serverErrorSub: "El cambio se guardó localmente",
        sessionExpiredTitle: "Sesión expirada",
        sessionExpiredSub: "Inicia sesión nuevamente",
        loginSuccessTitle: "Sesión iniciada",
        loginSyncedSub: "Datos sincronizados con la nube",
        loginOfflineSub: "Sin conexión — los datos se sincronizarán después",
    },
}

export const en = {
    appJS: {
        summary: "Summary",
        transactions: "Transactions",
        wallet: "Wallet",
        settings: "Settings"
    },
    createUserScreen: {
        welcomeTxt: "Welcome to ",
        chooseLanguage: "Choose your language",
        enterFName: "Enter your first name",
        acceptBtn: "Continue"
    },
    createAccountsScreen: {
        welcome: "Hello, ",
        registerTxt: "Before we start, let's register your liquid accounts (e.g., debit cards, digital wallets, or cash).",
        registerTDC: "You'll be able to add your credit cards on the next screen.",
        noAccounts: "Please add at least one liquid account.",
        bank: "Bank",
        cash: "Cash",
        savings: "Savings",
        startBtn: "Next",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        accountName: "Account's Name"
    },
    createCCScreen: {
        header1: "Add your ",
        header2: "Credit Cards",
        registerTxt: "Now, let's add your credit cards to complete the account setup.",
        onlyAdd: "Please only enter the total amount you owe to each card.",
        registerTDC: "You can skip this screen if you don't have credit cards.",
        noAccounts: "Please add at least one liquid account.",
        bank: "Bank Credit",
        startBtn: "Continue",
        noCC: "I don't have credit cards. (Skip)",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        accountName: "Account's Name"
    },
    mainScreen: {
        headerDarkTxt: "Hello, ",
        rowDescription: "Balance in ",
        transferBtn: " Transfer",
        hideBtn: " Hide Totals",
        summaryTitle: "Monthly Summary",
        income: "Income: ",
        expenses: "Expenses: ",
    },
    transactionsScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Transactions",
        searchPlaceHolder: "Search by description",
        selectTypeAll: "All",
        selectTypeIncome: "Income",
        selectTypeExpenses: "Expenses",
        emptyListTxt: "No transactions",
    },
    walletScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Wallet",
        title1: "Transfer Between Your Accounts",
        title2: "Edit Your Accounts",
        isCC: "Is Credit Card",
        amountTxt: "Amount:",
        fromTxt: "From:",
        toTxt: "To:",
        btnTransfer: "Transfer",
        btnTransfering: "Transferring...",
        addAccountBtn: "Add Account",
        modalAddAccountTitle: "Add a New Account",
        modalEditAccountTitle: "Edit an Account",
        chooseIconTxt: "Choose an Icon",
        cancelBtnTxt: "Cancel",
        createBtnTxt: "Create",
        saveBtnTxt: "Save",
        alertFailedTransferTitle: "Transaction Failed",
        alertFailedTransferDesc: "You do not have sufficient funds in the selected account.",
        alertSameAccountTitle: "Invalid Account",
        alertSameAccountDesc: "You cannot transfer to the same account.",
        alertFailedDeleAccTitle: "Error Deleting",
        alertFailedDeleAccDesc: "You cannot delete an account with existing funds. Please transfer your balance to another account first.",
        deleteAccountTitle: "Delete account?",
        deleteAccountDesc: "This account will be permanently deleted, along with its transactions. This action cannot be undone.",
    },
    typeTransactionScreen: {
        addIncomeTxt: "Add an Income",
        addExpenseTxt: "Add an Expense",
    },
    iaTransactionsScreen: {
        title: "Voice Transaction",
        subtitleIdle: "Describe your transaction",
        subtitleRecording: "Listening...",
        subtitleProcessing: "Processing...",
        hintIdle: "Tap to speak",
        hintRecording: "Tap to stop and process",
        retryBtn: "Record again",
        helpBtn: "?",
        helpTitle: "Welcome to the ExpensIA model",
        helpHowToUseTitle: "How to use",
        helpHowToUseBody: "Press the microphone button and mention one transaction. Include: amount, type (income or expense), account, date, and a short detail. You can use natural date language like 'yesterday', 'the day before yesterday', or '15 days ago'. For example: 'I paid 250 pesos for food yesterday with my BofA.'",
        helpLimitationsTitle: "Limitations",
        helpLimitationsBody: "ExpensIA can only process one transaction per request, so avoid mentioning multiple movements in a single recording.",
        helpCloseBtn: "Got it",
        alertBackendTitle: "Backend response",
        alertNoResponse: "No response",
        alertOkBtn: "OK",
        errorStartRecording: "Could not start recording",
        errorProcessing: "Processing error",
        errorGeneric: "Something went wrong",
        errorRetry: "Could not restart recording",
        loadingMsgs: [
            "Working some financial magic ✨",
            "Negotiating with the universe to boost your balance...",
            "Counting your coins... twice, just to be sure 🧐",
            "Chatting with my imaginary accountant...",
            "Optimizing your millionaire future (no pressure)...",
            "Convincing the AI not to spend your money...",
            "Analyzing if that was a expense... or an investment 👀",
            "Looking for that receipt you swore you'd keep...",
            "Making Excel proud of you 📊",
            "Calculating how many coffees you could've skipped ☕",
            "Asking ChatGPT… wait, I'm ExpensIA 🤖",
            "Fine-tuning your finances with surgical precision...",
            "Simulating your life as a millionaire 💸",
            "Checking if that counts as a 'micro-expense'...",
            "Consulting the budget gods...",
        ],
    },
    transactionScreen: {
        iaBannerLabel: "AI-generated",
        iaBannerTranscript: "You said:",
        headerRegister: "Register ",
        headerEdit: "Edit ",
        headerIncome: "Income",
        headerExpense: "Expense",
        amount: "Amount:",
        account: "Account:",
        date: "Date:",
        description: "Description",
        optional: "(Optional):",
        saveBtn: "Save",
        savingTxt: "Saving...",
        category: "Category:"
    },
    settingsScreen: {
        headerDarkTxt: "My ",
        headerGradientTxt: "Settings",
        changeLanguage: "Change Language",
        descriptionLanguage: "Current Language: ",
        editName: "Edit my name",
        descriptionName: "Current Name: ",
        changePrivacy: "Privacy in Totals",
        descriptionPrivacy: "Hide or show your totals.",
        customCategories: "My Categories",
        descriptionCategories: "Create and manage your categories.",
        deleteTransactions: "Delete Transactions",
        descriptionTransactions: "Only transactions will be deleted.",
        deleteAll: "Delete All Data",
        descriptionAll: "The app will be reset from scratch.",
        cancelBtn: "Cancel",
        acceptBtn: "Accept",
        deleteBtn: "Delete",
        deleteTransactionsModal: "Are you sure you want to delete all your transactions? Your transactions will be permanently deleted.",
        deleteAllModal: "Are you sure you want to delete all your data? The app will delete all your data and it will be permanently removed.",
        enterFName: "Enter your first name",
        logout: "Log out",
        logoutSession: "Session:",
        logoutModalTitle: "Log out?",
        logoutModalDesc: "Your cloud session will end on this device. Your local data will not be deleted.",
    },
    customCategoriesScreen: {
        headerDark: "My ",
        headerGradient: "Categories",
        sectionExpenses: "Expenses",
        sectionIncome: "Income",
        empty: "You have no custom categories yet.",
        deleteCatTitle: "Delete category?",
        deleteCatDesc: "The category will be deleted. Existing transactions will not be affected.",
    },
    createCategorySheet: {
        createTitle: "New category",
        editTitle: "Edit category",
        nameLabel: "Name",
        namePlaceholder: "E.g: Gym, Pet...",
        typeLabel: "Type",
        typeExpense: "Expense",
        typeIncome: "Income",
        iconLabel: "Icon",
        saveBtn: "Save",
        saving: "Saving...",
        newCategoryBtn: "New category",
        myCategoriesLabel: "My categories",
    },
    transactionCard: {
        typeIncome: "Income",
        typeExpense: "Expense",
        account: "Account: ",
        date: "Date: ",
        category: "Category: ",
        description: "Description: ",
        noDescription: "No description."
    },
    modalSelect: {
        chooseAccount: 'Select Your Account'
    },
    monthYearPicker: {
        title: "Month & year",
        confirm: "OK",
        cancel: "Cancel",
    },
    modalDelete: {
        titleDeleteTran: "Are you sure you want to delete this transaction?",
        descriptionDeleteTran: "Your transaction will be permanently deleted and your account totals will be updated.",
        cancelBtn: "Cancel",
        deleteBtn: "Delete",
    },
    toast: {
        savedLocal: "Saved",
        saveFailed: "Could not save",
        savedSynced: "Saved and synced",
        savedOfflineTitle: "Saved offline",
        savedOfflineSub: "Will sync when you're back online",
        serverErrorTitle: "Server error",
        serverErrorSub: "Your change was saved locally",
        sessionExpiredTitle: "Session expired",
        sessionExpiredSub: "Please sign in again",
        loginSuccessTitle: "Signed in",
        loginSyncedSub: "Data synced with the cloud",
        loginOfflineSub: "Offline — data will sync when you're back online",
    },
}